# Generated by Django 5.2.3 on 2025-07-19 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_article_content_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='journalist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journalist_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
