# Generated by Django 5.2.3 on 2025-07-19 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_alter_article_journalist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='published_articles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscriptions_journalists',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'journalist'}, related_name='subscribed_readers', to=settings.AUTH_USER_MODEL),
        ),
    ]
