# Generated by Django 5.2.3 on 2025-07-19 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_remove_article_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='journalists',
        ),
        migrations.AddField(
            model_name='journalist',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalist',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='journalists', to='newsapp.publisher'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='newsapp.publisher'),
        ),
        migrations.AlterField(
            model_name='journalist',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'journalist'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
